### ISSUE TITLE
Infografia de Gestion de Proyectos de Software

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-IsraelNicolas61#2]
[Infografia Gestion de Proyectos de Software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-IsraelNicolas61/files/9422021/Infografia.Gestion.de.Proyectos.de.Software.pdf)

**Comment by josealfredo79** [comment]
Calificación 19
Bien hecho y revisado
